--CHECK ALL PASSWORD AND PROFILE
col USERNAME for a30
col EXPIRY_DATE for a25
col ACCOUNT_STATUS for a20
select USERNAME, EXPIRY_DATE, ACCOUNT_STATUS from dba_users;

--CHECK TEH PASSWORD
select name, password from user$ where name='CT_PRDBLOC';

--VERIFICA EM QUAL PROFILE O USUARIO ESTA
select USERNAME,ACCOUNT_STATUS,PROFILE, EXPIRY_DATE  from dba_users where USERNAME='SAP_LAS_EPM';

-- altera o profile default para ter senhas que não expiram
ALTER PROFILE DEFAULT LIMIT FAILED_LOGIN_ATTEMPTS UNLIMITED PASSWORD_LIFE_TIME UNLIMITED;

-- Cria o profile LIVRE
create profile LIVRES limit PASSWORD_REUSE_TIME UNLIMITED PASSWORD_VERIFY_FUNCTION null PASSWORD_LIFE_TIME UNLIMITED PASSWORD_GRACE_TIME UNLIMITED PASSWORD_REUSE_MAX UNLIMITED ;

--COLOCA O USUARIO QUE DESEJA NO PROFILE LIVRE
alter user SAP_LAS_EPM profile LIVRES;
alter user KORAMON profile DE;
--COLACA A MESMA SENHA CRIPTOGRAFADA QUE VOLTOU A CIMA
ALTER USER SAP_LAS_EPM IDENTIFIED BY values 'D01747E22DB5DB8C' account unlock;
ALTER USER KYNORAMON IDENTIFIED BY values 'S:DEB5989F1270A71D8695E3C89314AEAEE66DAD10230B9349BB018CF1FD43;T:239A362ED8429A2ABD618FCA65CB64252817AC94CC4332440EFE16CC7DD15A4DC1A20B537660043DFB7FC22EBA4CA899896CCCEDFE6923DFE62C7EA641E49271B53589106C66B7F2B5DE005077552EDB' account unlock;
ALTER USER SAP_LAS_SOP IDENTIFIED BY values '7BC5D6183B4586EC' account unlock;
ALTER USER CT_PRDBLOC IDENTIFIED BY rman5ibm account unlock;

rman5ibm@RMAN

--VERIFICA SE O USUARIO AGORA ESTA OPEN
select USERNAME,ACCOUNT_STATUS,PROFILE, EXPIRY_DATE  from dba_users where USERNAME='CT_PRDBLOC';

--VOLTA O USUARIO PARA O PROFILE QUE ELE ESTAVA
alter user SAP_LAS_EPM profile DEFAULT;

--CERTIFICA QUE ELE VOLTOU PARA O PROFILE E ESTA OPEN
select USERNAME,ACCOUNT_STATUS,PROFILE, EXPIRY_DATE  from dba_users where USERNAME='SAP_LAS_EPM';

--DELETA O PROFILE QUE CRIAMOS PARA RENOVAR A SENHA
DROP PROFILE LIVRES;

--VERIFICA NOVAMENTE TODOS USUARIOS
col USERNAME for a30
col EXPIRY_DATE for a25
col ACCOUNT_STATUS for a20
select USERNAME, EXPIRY_DATE, ACCOUNT_STATUS from dba_users;



