-- Criar um usuário de teste
CREATE USER TESTE_DB IDENTIFIED BY senha123;
GRANT CONNECT, RESOURCE TO TESTE_DB;
ALTER USER TESTE_DB DEFAULT TABLESPACE USERS;
ALTER USER TESTE_DB QUOTA UNLIMITED ON USERS;

-- Conectar ao usuário TESTE_DB
ALTER SESSION SET CURRENT_SCHEMA = TESTE_DB;

-- Criar tabela de clientes
CREATE TABLE CLIENTES (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR2(100),
    EMAIL VARCHAR2(100),
    DATA_CADASTRO DATE DEFAULT SYSDATE
);

-- Criar tabela de produtos
CREATE TABLE PRODUTOS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR2(100),
    PRECO NUMBER(10,2),
    ESTOQUE NUMBER
);

-- Criar tabela de pedidos
CREATE TABLE PEDIDOS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CLIENTE_ID NUMBER,
    DATA_PEDIDO DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(20) DEFAULT 'PENDENTE',
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(ID)
);

-- Criar tabela de itens do pedido
CREATE TABLE ITENS_PEDIDO (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PEDIDO_ID NUMBER,
    PRODUTO_ID NUMBER,
    QUANTIDADE NUMBER,
    PRECO_UNITARIO NUMBER(10,2),
    FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDOS(ID),
    FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTOS(ID)
);

-- Inserir dados fictícios
INSERT INTO CLIENTES (NOME, EMAIL) VALUES ('João Silva', 'joao@email.com');
INSERT INTO CLIENTES (NOME, EMAIL) VALUES ('Maria Souza', 'maria@email.com');
INSERT INTO CLIENTES (NOME, EMAIL) VALUES ('Carlos Oliveira', 'carlos@email.com');

INSERT INTO PRODUTOS (NOME, PRECO, ESTOQUE) VALUES ('Notebook', 3500.00, 10);
INSERT INTO PRODUTOS (NOME, PRECO, ESTOQUE) VALUES ('Mouse', 150.00, 50);
INSERT INTO PRODUTOS (NOME, PRECO, ESTOQUE) VALUES ('Teclado', 200.00, 30);

INSERT INTO PEDIDOS (CLIENTE_ID) VALUES (1);
INSERT INTO PEDIDOS (CLIENTE_ID) VALUES (2);

INSERT INTO ITENS_PEDIDO (PEDIDO_ID, PRODUTO_ID, QUANTIDADE, PRECO_UNITARIO) VALUES (1, 1, 1, 3500.00);
INSERT INTO ITENS_PEDIDO (PEDIDO_ID, PRODUTO_ID, QUANTIDADE, PRECO_UNITARIO) VALUES (2, 2, 2, 150.00);

COMMIT;








 set linesize 1000
        set pagesize 1000
        COLUMN object_name FORMAT a50
        COLUMN OWNER FORMAT A15
        SELECT object_name,owner 
            FROM dba_objects 
            WHERE owner = 'TESTE_DB' 
            AND object_type IN ('TABLE', 'VIEW');