SGC.ADM.JOBS.UNX.IBM.TSM.BKP_FCP_OFF_P52_MTY.S100 - ORACLE - cd log DO BANDO DE DADOS
SGC.ADM.JOBS.UNX.IBM.TSM.BKP_FCP_OFF_P52_MTY.S200 - UNIX   - SPLIT - COPIA DA IMAGEM E MONTA OS FILESYSTEMS NO TSM
SGC.ADM.JOBS.UNX.IBM.TSM.BKP_FCP_OFF_P52_MTY.S300 - ORACLE - START DO BANCO DE DADOS
SGC.ADM.JOBS.UNX.IBM.TSM.BKP_FCP_OFF_P52_MTY.S400 - ORACLE - MONTA O BANCO NO SERVER TSM PARA BKP
SGC.ADM.JOBS.UNX.IBM.TSM.BKP_FCP_OFF_P52_MTY.S500 - STORAGE / UNIX   - SALVA EM FITA DO BKP NO TSM
SGC.ADM.JOBS.UNX.IBM.TSM.BKP_FCP_OFF_P52_MTY.S600 - ORACLE - DESMONTA O BANCO NO SERVER NO TSM
SGC.ADM.JOBS.UNX.IBM.TSM.BKP_FCP_OFF_P52_MTY.S700 - UNIX   - DESMONTA OS FILESYSTEMS DO BKP NO TSM